# Generated by Django 6.0 on 2025-12-06 08:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Field',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название поля')),
                ('area_hectares', models.FloatField(verbose_name='Площадь (га)')),
                ('crop_type', models.CharField(default='Cotton', max_length=50, verbose_name='Культура')),
                ('latitude', models.FloatField(verbose_name='Широта (Lat)')),
                ('longitude', models.FloatField(verbose_name='Долгота (Lon)')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Владелец')),
            ],
        ),
        migrations.CreateModel(
            name='SensorLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Время измерения')),
                ('soil_moisture', models.FloatField(verbose_name='Влажность почвы (%)')),
                ('air_temperature', models.FloatField(blank=True, null=True, verbose_name='Температура воздуха (°C)')),
                ('irrigation_needed', models.BooleanField(default=False, verbose_name='Требуется полив')),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sensor_logs', to='agronomy.field')),
            ],
        ),
    ]
