# Generated by Django 6.0 on 2025-12-06 09:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agronomy', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SeedVariety',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('recommended_soil', models.CharField(max_length=100)),
                ('expected_yield', models.FloatField(help_text='Ожидаемый урожай ц/га')),
            ],
        ),
        migrations.RemoveField(
            model_name='field',
            name='area_hectares',
        ),
        migrations.RemoveField(
            model_name='field',
            name='crop_type',
        ),
        migrations.RemoveField(
            model_name='field',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='field',
            name='longitude',
        ),
        migrations.RemoveField(
            model_name='sensorlog',
            name='air_temperature',
        ),
        migrations.RemoveField(
            model_name='sensorlog',
            name='irrigation_needed',
        ),
        migrations.AddField(
            model_name='field',
            name='irrigation_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='field',
            name='polygon_data',
            field=models.JSONField(blank=True, null=True, verbose_name='GeoJSON полигона'),
        ),
        migrations.AddField(
            model_name='sensorlog',
            name='weather_temp',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='field',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='field',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='sensorlog',
            name='field',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agronomy.field'),
        ),
        migrations.AlterField(
            model_name='sensorlog',
            name='soil_moisture',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='sensorlog',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AddField(
            model_name='field',
            name='seed_variety',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='agronomy.seedvariety'),
        ),
    ]
