# Generated by Django 6.0 on 2025-12-06 12:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agronomy', '0002_seedvariety_remove_field_area_hectares_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensorlog',
            name='irrigation_needed',
            field=models.BooleanField(default=False, verbose_name='Нужен полив?'),
        ),
        migrations.AddField(
            model_name='sensorlog',
            name='ml_message',
            field=models.CharField(blank=True, max_length=255, verbose_name='Вердикт AI'),
        ),
        migrations.AlterField(
            model_name='field',
            name='irrigation_active',
            field=models.BooleanField(default=False, verbose_name='Полив включен'),
        ),
        migrations.AlterField(
            model_name='field',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Название поля'),
        ),
        migrations.AlterField(
            model_name='sensorlog',
            name='field',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='agronomy.field'),
        ),
        migrations.AlterField(
            model_name='sensorlog',
            name='soil_moisture',
            field=models.FloatField(verbose_name='Влажность (%)'),
        ),
        migrations.AlterField(
            model_name='sensorlog',
            name='weather_temp',
            field=models.FloatField(blank=True, null=True, verbose_name='Температура воздуха (°C)'),
        ),
    ]
