# Generated by Django 5.2.9 on 2025-12-07 06:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agronomy', '0003_sensorlog_irrigation_needed_sensorlog_ml_message_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IrrigationPrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('location_x', models.FloatField()),
                ('location_y', models.FloatField()),
                ('predicted_humidity', models.FloatField(help_text='Predicted soil humidity for tomorrow')),
                ('current_humidity', models.FloatField(help_text='Current soil humidity')),
                ('dry_risk', models.BooleanField(default=False, help_text='Is there a drought risk?')),
                ('risk_level', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='low', max_length=20)),
                ('irrigation_action', models.CharField(choices=[('IRRIGATE', 'Irrigate'), ('SKIP', 'Skip')], default='SKIP', max_length=20)),
                ('recommended_irrigation', models.FloatField(help_text='Recommended irrigation amount in m3/mu')),
                ('is_future', models.BooleanField(default=False, help_text='Is this a future prediction?')),
                ('confidence_score', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='irrigation_predictions', to='agronomy.field')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='IrrigationEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('amount', models.FloatField(help_text='Amount in m3/mu')),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='irrigation_events', to='agronomy.field')),
                ('prediction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actual_events', to='agronomy.irrigationprediction')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='SensorReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('location_x', models.FloatField(db_index=True)),
                ('location_y', models.FloatField(db_index=True)),
                ('soil_humidity', models.FloatField(help_text='Soil humidity percentage')),
                ('soil_temperature', models.FloatField(help_text='Soil temperature in Celsius')),
                ('rain', models.FloatField(default=0, help_text='Daily rainfall in mm')),
                ('daily_mean_temperature', models.FloatField(help_text='Air temperature in Celsius')),
                ('irrigation_amount', models.FloatField(default=0, help_text='Irrigation in m3/mu')),
                ('days_since_irrigation', models.IntegerField(default=-1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='water_readings', to='agronomy.field')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.AddIndex(
            model_name='irrigationprediction',
            index=models.Index(fields=['field', 'date', 'is_future'], name='agronomy_ir_field_i_d291d7_idx'),
        ),
        migrations.AddIndex(
            model_name='sensorreading',
            index=models.Index(fields=['field', 'date'], name='agronomy_se_field_i_78e27e_idx'),
        ),
        migrations.AddIndex(
            model_name='sensorreading',
            index=models.Index(fields=['location_x', 'location_y'], name='agronomy_se_locatio_5e3d1e_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='sensorreading',
            unique_together={('field', 'date', 'location_x', 'location_y')},
        ),
    ]
