# Generated by Django 6.0 on 2025-12-07 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agronomy', '0003_sensorlog_irrigation_needed_sensorlog_ml_message_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='field',
            name='is_smart_mode',
            field=models.BooleanField(default=True, verbose_name='Авто-режим AI'),
        ),
        migrations.AddField(
            model_name='sensorlog',
            name='air_humidity',
            field=models.FloatField(blank=True, null=True, verbose_name='Влажность воздуха (%)'),
        ),
        migrations.AddField(
            model_name='sensorlog',
            name='drought_risk',
            field=models.CharField(choices=[('LOW', '🟢 Низкий риск'), ('MEDIUM', '🟡 Средний риск'), ('HIGH', '🔴 Высокий риск засухи')], default='LOW', max_length=20, verbose_name='Риск засухи'),
        ),
        migrations.AddField(
            model_name='sensorlog',
            name='rain_probability',
            field=models.FloatField(default=0, verbose_name='Вероятность дождя (%)'),
        ),
        migrations.AddField(
            model_name='sensorlog',
            name='recommended_water_amount',
            field=models.FloatField(default=0, verbose_name='Сколько литров/м²'),
        ),
        migrations.AlterField(
            model_name='field',
            name='irrigation_active',
            field=models.BooleanField(default=False, verbose_name='Полив включен (Статус клапана)'),
        ),
        migrations.AlterField(
            model_name='sensorlog',
            name='irrigation_needed',
            field=models.BooleanField(default=False, verbose_name='Рекомендация: Полив нужен?'),
        ),
        migrations.AlterField(
            model_name='sensorlog',
            name='soil_moisture',
            field=models.FloatField(verbose_name='Влажность почвы (%)'),
        ),
    ]
