# Generated by Django 5.2.9 on 2025-12-07 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agronomy', '0004_field_is_smart_mode_sensorlog_air_humidity_and_more'),
        ('agronomy', '0004_irrigationprediction_irrigationevent_sensorreading_and_more'),
    ]

    operations = [
    ]
