# Generated by Django 6.0 on 2025-12-06 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CottonBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_code', models.CharField(blank=True, help_text='QR код (генерируется автоматически)', max_length=50, unique=True)),
                ('harvest_date', models.DateField(auto_now_add=True)),
                ('initial_weight', models.FloatField(help_text='Вес при сборе (кг)')),
                ('fiber_length', models.FloatField(blank=True, help_text='Длина волокна (мм)', null=True)),
                ('micr', models.FloatField(blank=True, help_text='Микронейр (зрелость)', null=True)),
                ('trash_content', models.FloatField(blank=True, help_text='Засоренность (%)', null=True)),
                ('moisture', models.FloatField(blank=True, help_text='Влажность (%)', null=True)),
                ('strength', models.FloatField(blank=True, help_text='Удельная прочность (г/текс)', null=True)),
                ('color_grade', models.CharField(blank=True, help_text='Сорт по цвету (напр. White, Spotted)', max_length=20, null=True)),
                ('status', models.CharField(choices=[('HARVESTED', 'Собрано на поле'), ('TRANSIT', 'В пути на завод'), ('LAB_TESTING', 'В лаборатории'), ('PROCESSING', 'Обработка'), ('STORED', 'На складе')], default='HARVESTED', max_length=20)),
                ('blockchain_hash', models.CharField(blank=True, help_text='Хеш записи в блокчейне', max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
