# Generated by Django 6.0 on 2025-12-06 09:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factory', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('status', models.CharField(default='OK', max_length=20)),
                ('last_temp', models.FloatField(default=0)),
                ('last_vibration', models.FloatField(default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name='cottonbatch',
            name='blockchain_hash',
        ),
        migrations.RemoveField(
            model_name='cottonbatch',
            name='color_grade',
        ),
        migrations.RemoveField(
            model_name='cottonbatch',
            name='harvest_date',
        ),
        migrations.RemoveField(
            model_name='cottonbatch',
            name='initial_weight',
        ),
        migrations.RemoveField(
            model_name='cottonbatch',
            name='moisture',
        ),
        migrations.RemoveField(
            model_name='cottonbatch',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='cottonbatch',
            name='cotton_image',
            field=models.ImageField(blank=True, null=True, upload_to='cotton_images/', verbose_name='Фото хлопка'),
        ),
        migrations.AddField(
            model_name='cottonbatch',
            name='grade',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Сорт'),
        ),
        migrations.AddField(
            model_name='cottonbatch',
            name='hvi_file',
            field=models.FileField(blank=True, null=True, upload_to='hvi_docs/', verbose_name='HVI CSV/Excel'),
        ),
        migrations.AlterField(
            model_name='cottonbatch',
            name='batch_code',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='cottonbatch',
            name='farmer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='cottonbatch',
            name='fiber_length',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cottonbatch',
            name='micr',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cottonbatch',
            name='status',
            field=models.CharField(default='RECEIVED', max_length=20),
        ),
        migrations.AlterField(
            model_name='cottonbatch',
            name='strength',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cottonbatch',
            name='trash_content',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='MaintenanceLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField()),
                ('is_prediction', models.BooleanField(default=False, verbose_name='Это прогноз AI?')),
                ('probability_failure', models.FloatField(default=0, verbose_name='Вероятность поломки %')),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='factory.machine')),
            ],
        ),
    ]
