# Generated by Django 6.0 on 2025-12-06 11:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factory', '0003_machine_remove_cottonbatch_blockchain_hash_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cottonbatch',
            name='fiber_length',
        ),
        migrations.RemoveField(
            model_name='cottonbatch',
            name='grade',
        ),
        migrations.RemoveField(
            model_name='cottonbatch',
            name='micr',
        ),
        migrations.RemoveField(
            model_name='cottonbatch',
            name='trash_content',
        ),
        migrations.AddField(
            model_name='cottonbatch',
            name='color_grade',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Color Grade (напр. 31-1)'),
        ),
        migrations.AddField(
            model_name='cottonbatch',
            name='length',
            field=models.FloatField(blank=True, null=True, verbose_name='Length (дюймы)'),
        ),
        migrations.AddField(
            model_name='cottonbatch',
            name='micronaire',
            field=models.FloatField(blank=True, null=True, verbose_name='Micronaire (3.5–4.9)'),
        ),
        migrations.AddField(
            model_name='cottonbatch',
            name='quality_class',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Итоговый класс (Target)'),
        ),
        migrations.AddField(
            model_name='cottonbatch',
            name='sci',
            field=models.IntegerField(blank=True, null=True, verbose_name='Spinning Consistency Index (SCI)'),
        ),
        migrations.AddField(
            model_name='cottonbatch',
            name='sfi',
            field=models.FloatField(blank=True, null=True, verbose_name='Short Fiber Index (SFI)'),
        ),
        migrations.AddField(
            model_name='cottonbatch',
            name='trash_area',
            field=models.FloatField(blank=True, null=True, verbose_name='Trash Area (%)'),
        ),
        migrations.AddField(
            model_name='cottonbatch',
            name='trash_cnt',
            field=models.IntegerField(blank=True, null=True, verbose_name='Trash Count (шт)'),
        ),
        migrations.AddField(
            model_name='cottonbatch',
            name='trash_grade',
            field=models.IntegerField(blank=True, null=True, verbose_name='Trash Grade (1-7)'),
        ),
        migrations.AddField(
            model_name='cottonbatch',
            name='uniformity',
            field=models.FloatField(blank=True, null=True, verbose_name='Uniformity (%)'),
        ),
        migrations.AlterField(
            model_name='cottonbatch',
            name='batch_code',
            field=models.CharField(blank=True, max_length=50, unique=True, verbose_name='Код партии'),
        ),
        migrations.AlterField(
            model_name='cottonbatch',
            name='cotton_image',
            field=models.ImageField(blank=True, null=True, upload_to='cotton_images/', verbose_name='Фото образца'),
        ),
        migrations.AlterField(
            model_name='cottonbatch',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='cottonbatch',
            name='farmer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Фермер'),
        ),
        migrations.AlterField(
            model_name='cottonbatch',
            name='hvi_file',
            field=models.FileField(blank=True, null=True, upload_to='hvi_docs/', verbose_name='HVI файл (.csv/.xlsx)'),
        ),
        migrations.AlterField(
            model_name='cottonbatch',
            name='status',
            field=models.CharField(choices=[('RECEIVED', 'Принято'), ('ANALYZED', 'Проанализировано'), ('EXPORT_READY', 'Готово к экспорту')], default='RECEIVED', max_length=20, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='cottonbatch',
            name='strength',
            field=models.FloatField(blank=True, null=True, verbose_name='Strength (г/текс)'),
        ),
        migrations.AlterField(
            model_name='maintenancelog',
            name='is_prediction',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='maintenancelog',
            name='probability_failure',
            field=models.FloatField(default=0),
        ),
    ]
