# Generated by Django 6.0 on 2025-12-06 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factory', '0004_remove_cottonbatch_fiber_length_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cottonbatch',
            name='batch_code',
            field=models.CharField(blank=True, max_length=50, unique=True, verbose_name='Код партии (ID)'),
        ),
        migrations.AlterField(
            model_name='cottonbatch',
            name='hvi_file',
            field=models.FileField(blank=True, null=True, upload_to='hvi_docs/', verbose_name='HVI файл'),
        ),
        migrations.AlterField(
            model_name='cottonbatch',
            name='quality_class',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='★ Quality Class (Target)'),
        ),
    ]
