# Generated by Django 6.0 on 2025-12-06 14:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factory', '0005_alter_cottonbatch_batch_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='machine',
            name='last_humidity',
            field=models.FloatField(default=0, verbose_name='Влажность в цеху (%)'),
        ),
        migrations.AddField(
            model_name='machine',
            name='last_motor_load',
            field=models.FloatField(default=0, verbose_name='Нагрузка мотора (%)'),
        ),
        migrations.AddField(
            model_name='machine',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Последнее обновление'),
        ),
        migrations.AlterField(
            model_name='machine',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активен'),
        ),
        migrations.AlterField(
            model_name='machine',
            name='last_temp',
            field=models.FloatField(default=0, verbose_name='Температура (°C)'),
        ),
        migrations.AlterField(
            model_name='machine',
            name='last_vibration',
            field=models.FloatField(default=0, verbose_name='Вибрация'),
        ),
        migrations.AlterField(
            model_name='machine',
            name='name',
            field=models.CharField(max_length=100, verbose_name='ID Станка (GIN-01)'),
        ),
        migrations.AlterField(
            model_name='machine',
            name='status',
            field=models.CharField(default='OK', max_length=20, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='maintenancelog',
            name='description',
            field=models.TextField(verbose_name='Описание проблемы'),
        ),
        migrations.AlterField(
            model_name='maintenancelog',
            name='is_prediction',
            field=models.BooleanField(default=False, verbose_name='Это прогноз AI?'),
        ),
        migrations.AlterField(
            model_name='maintenancelog',
            name='machine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='factory.machine', verbose_name='Станок'),
        ),
        migrations.AlterField(
            model_name='maintenancelog',
            name='probability_failure',
            field=models.FloatField(default=0, verbose_name='Вероятность поломки (%)'),
        ),
    ]
