# Generated by Django 6.0 on 2025-12-07 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factory', '0006_machine_last_humidity_machine_last_motor_load_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cottonbatch',
            name='moisture',
            field=models.FloatField(blank=True, null=True, verbose_name='Влажность (%)'),
        ),
        migrations.AddField(
            model_name='cottonbatch',
            name='seed_variety',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Сорт семян'),
        ),
        migrations.AddField(
            model_name='cottonbatch',
            name='weight_kg',
            field=models.FloatField(default=0, verbose_name='Вес партии (кг)'),
        ),
    ]
