# Generated by Django 5.2.9 on 2025-12-07 13:58

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factory', '0006_machine_last_humidity_machine_last_motor_load_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='machine',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='machine',
            name='last_humidity',
        ),
        migrations.RemoveField(
            model_name='machine',
            name='last_motor_load',
        ),
        migrations.RemoveField(
            model_name='machine',
            name='last_temp',
        ),
        migrations.RemoveField(
            model_name='machine',
            name='last_vibration',
        ),
        migrations.RemoveField(
            model_name='machine',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='machine',
            name='humidity',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='machine',
            name='machine_type',
            field=models.CharField(default='Generic', help_text='Type of machine', max_length=50),
        ),
        migrations.AddField(
            model_name='machine',
            name='motor_load',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='machine',
            name='temperature',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='machine',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='machine',
            name='vibration',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='machine',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='machine',
            name='status',
            field=models.CharField(default='operational', max_length=20),
        ),
    ]
