# Generated by Django 6.0 on 2025-12-07 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factory', '0007_cottonbatch_moisture_cottonbatch_seed_variety_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cottonbatch',
            name='cv_confidence',
            field=models.FloatField(blank=True, null=True, verbose_name='Уверенность CV'),
        ),
        migrations.AddField(
            model_name='cottonbatch',
            name='cv_status',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Чистота (CV)'),
        ),
        migrations.AddField(
            model_name='cottonbatch',
            name='region',
            field=models.CharField(default='South', max_length=100, verbose_name='Регион выращивания'),
        ),
        migrations.AlterField(
            model_name='cottonbatch',
            name='batch_code',
            field=models.CharField(blank=True, max_length=50, unique=True, verbose_name='Код партии'),
        ),
        migrations.AlterField(
            model_name='cottonbatch',
            name='color_grade',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Color Grade'),
        ),
        migrations.AlterField(
            model_name='cottonbatch',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='cottonbatch',
            name='length',
            field=models.FloatField(blank=True, null=True, verbose_name='Length'),
        ),
        migrations.AlterField(
            model_name='cottonbatch',
            name='micronaire',
            field=models.FloatField(blank=True, null=True, verbose_name='Micronaire'),
        ),
        migrations.AlterField(
            model_name='cottonbatch',
            name='quality_class',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Класс качества (HVI)'),
        ),
        migrations.AlterField(
            model_name='cottonbatch',
            name='sci',
            field=models.IntegerField(blank=True, null=True, verbose_name='SCI'),
        ),
        migrations.AlterField(
            model_name='cottonbatch',
            name='sfi',
            field=models.FloatField(blank=True, null=True, verbose_name='SFI'),
        ),
        migrations.AlterField(
            model_name='cottonbatch',
            name='status',
            field=models.CharField(choices=[('RECEIVED', 'Принято'), ('ANALYZED', 'Проанализировано'), ('EXPORT_READY', 'Готово к экспорту')], default='RECEIVED', max_length=20),
        ),
        migrations.AlterField(
            model_name='cottonbatch',
            name='strength',
            field=models.FloatField(blank=True, null=True, verbose_name='Strength'),
        ),
        migrations.AlterField(
            model_name='cottonbatch',
            name='trash_area',
            field=models.FloatField(blank=True, null=True, verbose_name='Trash Area'),
        ),
        migrations.AlterField(
            model_name='cottonbatch',
            name='trash_cnt',
            field=models.IntegerField(blank=True, null=True, verbose_name='Trash Count'),
        ),
        migrations.AlterField(
            model_name='cottonbatch',
            name='trash_grade',
            field=models.IntegerField(blank=True, null=True, verbose_name='Trash Grade'),
        ),
        migrations.AlterField(
            model_name='cottonbatch',
            name='uniformity',
            field=models.FloatField(blank=True, null=True, verbose_name='Uniformity'),
        ),
    ]
