# Generated by Django 6.0 on 2025-12-07 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factory', '0008_cottonbatch_cv_confidence_cottonbatch_cv_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cottonbatch',
            name='seed_recommendations',
            field=models.JSONField(blank=True, null=True, verbose_name='Топ-3 Семена (AI)'),
        ),
    ]
