# Generated by Django 6.0 on 2025-12-07 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factory', '0009_cottonbatch_seed_recommendations'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenancelog',
            name='temperature',
            field=models.FloatField(default=0, verbose_name='Температура (°C)'),
        ),
        migrations.AddField(
            model_name='maintenancelog',
            name='vibration',
            field=models.FloatField(default=0, verbose_name='Вибрация'),
        ),
    ]
