# Generated by Django 5.2.9 on 2025-12-07 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('factory', '0007_remove_machine_is_active_and_more'),
        ('factory', '0010_maintenancelog_temperature_maintenancelog_vibration'),
    ]

    operations = [
    ]
