# Generated by Django 6.0 on 2025-12-06 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MarketPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commodity', models.CharField(default='Cotton', max_length=50)),
                ('price', models.FloatField()),
                ('date', models.DateField()),
                ('is_forecast', models.BooleanField(default=False, verbose_name='Это прогноз AI?')),
                ('confidence_score', models.FloatField(null=True, verbose_name='Уверенность AI %')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
