# Generated by Django 6.0 on 2025-12-06 08:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plate_number', models.CharField(max_length=20, unique=True, verbose_name='Гос. номер')),
                ('vehicle_type', models.CharField(choices=[('TRACTOR', 'Трактор'), ('TRUCK', 'Грузовик (КамАЗ/Volvo)')], max_length=20, verbose_name='Тип ТС')),
                ('is_active', models.BooleanField(default=True, verbose_name='На линии')),
                ('fuel_level', models.FloatField(default=100.0, verbose_name='Уровень топлива (%)')),
                ('driver', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Водитель')),
            ],
        ),
        migrations.CreateModel(
            name='GPSLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('speed', models.FloatField(default=0, verbose_name='Скорость (км/ч)')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gps_logs', to='logistics.vehicle')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
