# Generated by Django 6.0 on 2025-12-06 09:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle',
            name='fuel_level',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='vehicle_type',
        ),
        migrations.AddField(
            model_name='vehicle',
            name='status',
            field=models.CharField(default='IDLE', max_length=20, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='gpslog',
            name='speed',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='plate_number',
            field=models.CharField(max_length=20, verbose_name='Гос. номер'),
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('path_geojson', models.JSONField(verbose_name='Координаты пути')),
                ('estimated_time', models.IntegerField(verbose_name='Время в пути (мин)')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='logistics.vehicle')),
            ],
        ),
    ]
