# Generated by Django 6.0 on 2025-12-07 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0002_remove_vehicle_fuel_level_remove_vehicle_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='current_load',
            field=models.FloatField(default=0, verbose_name='Текущий вес груза (кг)'),
        ),
    ]
