# Generated by Django 5.2.9 on 2025-12-06 14:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0002_remove_vehicle_fuel_level_remove_vehicle_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активный маршрут'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='marker_color',
            field=models.CharField(default='#f97316', max_length=7, verbose_name='Цвет на карте'),
        ),
        migrations.AlterField(
            model_name='route',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routes', to='logistics.vehicle'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='status',
            field=models.CharField(choices=[('IDLE', 'Ожидает'), ('MOVING', 'В пути'), ('UNLOADING', 'Разгрузка')], default='IDLE', max_length=20, verbose_name='Статус'),
        ),
    ]
