# Generated by Django 5.2.9 on 2025-12-07 13:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0003_route_is_active_vehicle_marker_color_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Depot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Depot name')),
                ('latitude', models.FloatField(verbose_name='Latitude')),
                ('longitude', models.FloatField(verbose_name='Longitude')),
                ('is_default', models.BooleanField(default=False, verbose_name='Default depot')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Depot',
                'verbose_name_plural': 'Depots',
            },
        ),
        migrations.CreateModel(
            name='Field',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Field name')),
                ('latitude', models.FloatField(verbose_name='Latitude')),
                ('longitude', models.FloatField(verbose_name='Longitude')),
                ('demand', models.FloatField(default=1.0, help_text='Amount of cotton to collect', verbose_name='Demand (units)')),
                ('service_time_minutes', models.IntegerField(default=15, help_text='Time needed to service this field', verbose_name='Service time (minutes)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='vehicle',
            name='capacity',
            field=models.FloatField(default=20.0, help_text='Vehicle capacity in units', verbose_name='Capacity (units)'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='shift_minutes',
            field=models.IntegerField(default=480, help_text='Working shift duration in minutes', verbose_name='Shift duration (minutes)'),
        ),
        migrations.CreateModel(
            name='OptimizationJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('request_data', models.JSONField(verbose_name='Request data')),
                ('ors_request', models.JSONField(blank=True, null=True, verbose_name='ORS request payload')),
                ('ors_solution', models.JSONField(blank=True, null=True, verbose_name='ORS solution')),
                ('ai_summary', models.TextField(blank=True, help_text='Gemini AI generated summary', verbose_name='AI Summary')),
                ('status', models.CharField(default='pending', max_length=20, verbose_name='Status')),
                ('error_message', models.TextField(blank=True, verbose_name='Error message')),
                ('depot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='optimization_jobs', to='logistics.depot')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
