# Generated by Django 5.2.9 on 2025-12-07 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0003_vehicle_current_load'),
        ('logistics', '0004_depot_field_vehicle_capacity_vehicle_shift_minutes_and_more'),
    ]

    operations = [
    ]
