# Generated by Django 5.2.9 on 2025-12-07 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0005_merge_20251207_2334'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle',
            name='current_load',
        ),
    ]
