# Generated by Django 6.0 on 2025-12-06 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SafetyAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('FIRE', 'Пожар'), ('SMOKE', 'Дым'), ('NO_HELMET', 'Нет каски'), ('DANGER_ZONE', 'Человек в опасной зоне')], max_length=20)),
                ('location', models.CharField(max_length=100)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('is_resolved', models.BooleanField(default=False)),
                ('snapshot', models.ImageField(null=True, upload_to='safety_alerts/')),
            ],
        ),
    ]
