# Generated by Django 6.0 on 2025-12-06 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('safety', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='safetyalert',
            name='confidence',
            field=models.FloatField(blank=True, null=True, verbose_name='Точность AI'),
        ),
        migrations.AddField(
            model_name='safetyalert',
            name='detection_details',
            field=models.JSONField(blank=True, null=True, verbose_name='Детали (bbox)'),
        ),
        migrations.AlterField(
            model_name='safetyalert',
            name='alert_type',
            field=models.CharField(choices=[('FIRE', 'Пожар'), ('SMOKE', 'Дым'), ('NO_HELMET', 'Нет каски'), ('DANGER_ZONE', 'Человек в опасной зоне')], max_length=20, verbose_name='Тип угрозы'),
        ),
        migrations.AlterField(
            model_name='safetyalert',
            name='location',
            field=models.CharField(max_length=100, verbose_name='Камера/Зона'),
        ),
        migrations.AlterField(
            model_name='safetyalert',
            name='snapshot',
            field=models.ImageField(blank=True, null=True, upload_to='safety_alerts/'),
        ),
    ]
