# Generated by Django 6.0 on 2025-12-07 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('safety', '0002_safetyalert_confidence_safetyalert_detection_details_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkerHealthLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('worker_id', models.CharField(max_length=50, verbose_name='ID Сотрудника')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Время замера')),
                ('heart_rate', models.FloatField(verbose_name='Пульс (уд/мин)')),
                ('spo2', models.IntegerField(verbose_name='Кислород SpO2 (%)')),
                ('body_temp', models.FloatField(verbose_name='Температура (°C)')),
                ('stress_index', models.FloatField(verbose_name='Уровень стресса')),
                ('noise_level', models.FloatField(verbose_name='Уровень шума (дБ)')),
                ('steps', models.IntegerField(default=0, verbose_name='Шаги')),
                ('sleep_quality', models.IntegerField(default=0, verbose_name='Качество сна (%)')),
                ('status', models.CharField(choices=[('OK', 'Норма'), ('CRITICAL_PULSE', 'Критический пульс'), ('FEVER', 'Жар/Лихорадка'), ('HYPOXIA', 'Гипоксия (мало кислорода)'), ('HIGH_STRESS', 'Высокий стресс'), ('DANGEROUS_NOISE', 'Опасный уровень шума')], default='OK', max_length=20, verbose_name='Статус здоровья')),
            ],
        ),
    ]
