# Generated by Django 6.0 on 2025-12-07 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('safety', '0003_workerhealthlog'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='safetyalert',
            options={'ordering': ['-timestamp'], 'verbose_name': 'Тревожный сигнал (AI)', 'verbose_name_plural': 'Тревожные сигналы (AI)'},
        ),
        migrations.AlterField(
            model_name='safetyalert',
            name='alert_type',
            field=models.CharField(choices=[('FIRE', '🔥 Пожар'), ('SMOKE', '💨 Дым'), ('NO_HELMET', '👷 Нет каски'), ('DANGER_ZONE', '⚠️ Опасная зона')], max_length=20, verbose_name='Тип угрозы'),
        ),
        migrations.AlterField(
            model_name='safetyalert',
            name='confidence',
            field=models.FloatField(blank=True, null=True, verbose_name='Точность AI (0.0-1.0)'),
        ),
        migrations.AlterField(
            model_name='safetyalert',
            name='detection_details',
            field=models.JSONField(blank=True, null=True, verbose_name='Детали (координаты bbox)'),
        ),
        migrations.AlterField(
            model_name='safetyalert',
            name='is_resolved',
            field=models.BooleanField(default=False, verbose_name='Проблема решена?'),
        ),
        migrations.AlterField(
            model_name='safetyalert',
            name='snapshot',
            field=models.ImageField(blank=True, null=True, upload_to='safety_alerts/', verbose_name='Снимок с камеры'),
        ),
        migrations.AlterField(
            model_name='safetyalert',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Время обнаружения'),
        ),
    ]
