# Generated by Django 5.2.9 on 2025-12-07 17:39

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('safety', '0004_alter_safetyalert_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('worker_id', models.IntegerField(unique=True, verbose_name='Worker ID')),
                ('name', models.CharField(max_length=100, verbose_name='Full Name')),
                ('role', models.CharField(max_length=100, verbose_name='Role/Position')),
                ('latitude', models.FloatField(default=0.0, verbose_name='Latitude')),
                ('longitude', models.FloatField(default=0.0, verbose_name='Longitude')),
                ('altitude', models.FloatField(default=0.0, verbose_name='Altitude (m)')),
                ('heart_rate', models.FloatField(default=75.0, verbose_name='Heart Rate (BPM)')),
                ('steps', models.IntegerField(default=0, verbose_name='Steps Count')),
                ('activity_level', models.IntegerField(default=0, verbose_name='Activity Level (0-10)')),
                ('temp_c', models.FloatField(default=36.6, verbose_name='Body Temperature (°C)')),
                ('spo2', models.IntegerField(default=98, verbose_name='Blood Oxygen (%)')),
                ('noise_level', models.FloatField(default=60.0, verbose_name='Ambient Noise (dB)')),
                ('hrv', models.FloatField(default=50.0, verbose_name='Heart Rate Variability (ms)')),
                ('sleep_score', models.IntegerField(default=80, verbose_name='Sleep Score (0-100)')),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Worker',
                'verbose_name_plural': 'Workers',
                'ordering': ['worker_id'],
            },
        ),
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Zone Name')),
                ('zone_type', models.CharField(choices=[('CHEMICAL', 'Chemical Storage'), ('ASSEMBLY', 'Assembly Line'), ('LOADING', 'Loading Dock'), ('SAFE', 'Safe Zone')], default='SAFE', max_length=20)),
                ('lat_min', models.FloatField(verbose_name='Latitude Min')),
                ('lat_max', models.FloatField(verbose_name='Latitude Max')),
                ('lon_min', models.FloatField(verbose_name='Longitude Min')),
                ('lon_max', models.FloatField(verbose_name='Longitude Max')),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Zone',
                'verbose_name_plural': 'Zones',
            },
        ),
        migrations.CreateModel(
            name='WorkerHealthMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('heart_rate', models.FloatField(verbose_name='Heart Rate (BPM)')),
                ('spo2', models.IntegerField(verbose_name='Blood Oxygen (%)')),
                ('temp_c', models.FloatField(verbose_name='Body Temperature (°C)')),
                ('hrv', models.FloatField(verbose_name='HRV (ms)')),
                ('steps', models.IntegerField(verbose_name='Steps')),
                ('activity_level', models.IntegerField(verbose_name='Activity Level')),
                ('noise_level', models.FloatField(verbose_name='Noise Level (dB)')),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('altitude', models.FloatField()),
                ('alert_panic', models.BooleanField(default=False)),
                ('alert_fall', models.BooleanField(default=False)),
                ('alert_fatigue', models.BooleanField(default=False)),
                ('alert_environment', models.BooleanField(default=False)),
                ('alert_acoustic', models.BooleanField(default=False)),
                ('alert_geofence', models.BooleanField(default=False)),
                ('safety_status', models.CharField(default='OK', max_length=500)),
                ('zone', models.CharField(default='Safe Zone', max_length=100)),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='health_logs', to='safety.worker')),
            ],
            options={
                'verbose_name': 'Health Metric',
                'verbose_name_plural': 'Health Metrics',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['worker', '-timestamp'], name='safety_work_worker__98de20_idx')],
            },
        ),
    ]
